services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: uome-backend
    container_name: uome-backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=et
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend/app
        target: /code/app
    networks:
      - uome-network
    links:
      - database:database
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uome-frontend
    image: uome-frontend
    # env_file:
    #   - frontend/.env
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
      - type: bind
        source: ./frontend/node_modules
        target: /app/node_modules
      - nextjs_cache:/home/nextjs/app/.next/
    depends_on:
      - backend
    networks:
      - uome-network
    links:
      - backend:backend
    command: npm run dev

  database:
    image: postgres:16
    container_name: uome-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: et
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - uome-network



networks:
  uome-network:
    driver: bridge


volumes:
  database:
  nextjs_cache:
