services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: et-backend
    container_name: et-backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=et
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: et-frontend
    image: et-frontend
    ports:
      - 8501:8501
    volumes:
      - ./frontend/app:/app
    depends_on:
      - backend
    networks:
      - default

  database:
    image: postgres:16
    container_name: et-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: et
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default


networks:
  default:
    name: et-network


volumes:
  database:
