name: Deploy main to Fly
on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  migration:
    name: Run database migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run migrations
        working-directory: ./backend
        run: flyctl ssh console -C "poetry run alembic upgrade head"

  deploy:
    name: Deploy to Fly
    needs: migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        working-directory: ./backend
        run: flyctl deploy
