name: Deploy backend to Fly
on:
  push:
    branches: [ main ]
    paths:
      - backend/** # Only run on changes to the backend directory

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        working-directory: ./backend
        run: flyctl deploy

      - name: Run migrations
        working-directory: ./backend
        run: flyctl ssh console -C "poetry run alembic upgrade head"
