name: Ruff
on:
  push:
    path:
      - 'backend/**'
  pull_request:
    path:
      - 'backend/**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
